<?php defined('_ENGINE') or die('Access Denied'); return array (
  0 => 'Activity',
  1 => 'Advancedarticles',
  2 => 'Album',
  3 => 'Announcement',
  4 => 'Authorization',
  5 => 'Cometchat',
  6 => 'Core',
  7 => 'Fields',
  8 => 'Group',
  9 => 'Invite',
  10 => 'Messages',
  11 => 'Network',
  12 => 'Payment',
  13 => 'Sqlupdates',
  14 => 'Storage',
  15 => 'User',
  16 => 'Video',
  17 => 'Ynresponsive1',
  18 => 'Ynresponsivepurity',
  19 => 'Yntheme',
  20 => 'YounetCore',
); ?>