<?php

return array(
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Categories'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display articles categories'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.categories-block',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Bread Crumbs'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('It allows users to keep track of their locations'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.bredcrumbs-block',
  ),  
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Actions'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Main menu navigation (Browse Articles Home | Browse Articles | My Articles | Add New Article)'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.actions-block',
  ),  
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('View Article'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display articles title, body, info, comments etc...'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.article-block',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('List Articles'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays a list of posted articles with different filtering options'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.listarticle-block',
    'autoEdit' => true,
  ),  
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Owner Info'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display owner info (photo, total submitted articles and actions)'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.user-info',
    'defaultParams' => array(
      'title' => 'Owner',
    ),    
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Articles Archive'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display articles archive'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.arhive-block',
    'defaultParams' => array(
      'title' => 'Archives',
    ),    
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Filter Form'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display form to search for articles'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.filter-block',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Recent Articles'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays a list of recently articles'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.recent-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Recent',
  ), 
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Popular Tags'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display popular tag cloud'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.tags-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_ListingTags',
  ),     
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Most Commented'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays a list of most commented articles'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.comment-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Comment',
  ),  
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Most Viewed'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays a list of most viewed articles'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.view-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_View',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Most Liked'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays a list of most liked articles'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.like-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Like',
  ),   
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Random'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays a list of random articles'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.random-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Random',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Featured Articles'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display featured articles in slideshow format'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.featured-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Featured',
  ),  
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Sponsored Articles'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display sponsored articles in slideshow format'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.sponsored-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Sponsored',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Profile Articles'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays a members articles on their profile'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.profile-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Profile',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Related Articles'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display related articles by tags'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.related-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Related',
  ),
  array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Top Posters'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Displays list of top articles submitters'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.posters-block',
    'autoEdit' => true,
    'adminForm' => 'Advancedarticles_Form_Admin_Widget_Posters',
  ), 
   array(
    'title' => Zend_Registry::get('Zend_Translate')->translate('Trending Articles'),
    'description' => Zend_Registry::get('Zend_Translate')->translate('Display trending articles in slideshow format'),
    'category' => 'Advanced Articles',
    'type' => 'widget',
    'name' => 'advancedarticles.trending-articles',
    'autoEdit' => true,
    //'adminForm' => 'Advancedarticles_Form_Admin_Widget_trending',
  ),
  
) ?>